version: '3.2'

services:

    php:
      build: ./docker/php
      volumes:
        - ./web:/var/www/html

    web:
      image: nginx
      volumes:
        - ./web:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf