version: '3.2'

services:

    php:
      build: ./docker/php
      volumes:
        - ./web:/var/www

    web:
      image: nginx
      volumes:
        - ./web:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
      - php