version: '3.2'

services:

    php:
      build: ./docker/php
      volumes:
        - ./web:/var/www

    web:
      image: nginx
      volumes:
        - ./web:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
      - php

    db:
      image: mysql
      environment:
        MYSQL_ROOT_HOST: '%'
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: yii2-sample